better compiler invocation bash script

diff --git a/trunk/swiftc b/trunk/swiftc
--- a/trunk/swiftc
+++ b/trunk/swiftc
@@ -27,13 +27,35 @@ else
     exit -1
 fi
 
-./swift $in     # compile
-as $asm -o $obj # assemble output
+# compile
+./swift $in 
+
+if [ $? -ne 0 ]; then 
+    exit -1 # something went wrong
+fi
+
+# assemble output
+as $asm -o $obj 
+
+if [ $? -ne 0 ]; then 
+    echo "error: internal compiler error"
+    exit -1 # something went wrong
+fi
 
 # compile lib.c if necessary
 if [ ! -e 'test/lib.o' ]; then
     gcc -ggdb -c test/lib.c -o test/lib.o
 fi
 
+if [ $? -ne 0 ]; then 
+    echo "error: internal compiler error"
+    exit -1 # something went wrong
+fi
+
 # and link everything
 gcc -nostdlib -lc test/lib.o $obj -o $out $*
+
+if [ $? -ne 0 ]; then 
+    echo "error: internal compiler error"
+    exit -1 # something went wrong
+fi
